django_projects/semi_restful_users/apps/users/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^(?P<user_id>\d+)$', show, name='show'),
    url(r'^new$', new, name='new'),
    url(r'^edit/(?P<user_id>\d+)$', edit, name='edit'),
    url(r'^destroy/(?P<user_id>\d+)$', destroy, name='destroy'),
    url(r'^create$', create, name='create'),
    url(r'^update/(?P<user_id>\d+)$', update, name='update'),
]

django_projects/semi_restful_users/semi_restful_users/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^users/', include('apps.users.urls', namespace='users')),
    url(r'^admin/', admin.site.urls),
]

django_projects/semi_restful_users/apps/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255, unique=True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

django_projects/semi_restful_users/apps/users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, HttpResponse, redirect
from django.core.urlresolvers import reverse
from django.template import RequestContext

from models import *



# errors = Blog.objects.basic_validator(request.POST)


def index(request):
    all_users = User.objects.all()
    context= {
        "all_users" : all_users,
    }
    return render(request, "users/index.html",context)

def show(request,user_id):
    users = User.objects.get(id = user_id)
    context= {
        "users" : users,
    }
    
    return render(request, "users/show.html", context)

def new(request):
    return render(request, "users/new.html")

def edit(request, user_id):
    users = User.objects.get(id = user_id)
    context= {
        "users" : users,
    }
    return render(request, "users/edit.html", context)

def destroy(request, user_id):
    user = User.objects.get(id = user_id)
    user.delete()
    return redirect(reverse('users:index'))

def create(request):
    errors = {}
    if len(request.POST['first_name']) <= 2 or len(request.POST['email']) > 30:
        errors["first_name"] = "Blog name should be at least 2 characters"
    if len(request.POST['last_name']) <= 2 or len(request.POST['email']) > 30 :
        errors["last_name"] = "Blog name should be at least 2 characters"
    if len(request.POST['email']) <5 or len(request.POST['email']) >40:
        errors["email"] = "Blog desc should be more than 10 characters"  

    if not len(errors):
        success = User.objects.create(first_name = request.POST["first_name"], last_name = request.POST["last_name"],email = request.POST["email"])
        print success
    else:
        for key,value in errors:
            print "There is an error for %s: %S" % (key, value) 
    return redirect(reverse('users:index'))

def update(request,user_id):

    request.session.errors = []
    if len(request.POST['first_name']) <= 2 or len(request.POST['email']) > 30:
        request.session.errors.append("There is an error: First Name should be at least 2 characters and less than 30 characters")
    if len(request.POST['last_name']) <= 2 or len(request.POST['email']) > 30 :
        request.session.errors.append("There is an error: Last Name should be at least 2 characters and less than 30 characters")
    if len(request.POST['email']) <5 or len(request.POST['email']) >40:
        request.errors["email"] = "There is an error: Email should be at least 5 characters and less than 40 characters"  

    if not len(request.session.errors):
        update_user = User.objects.get(id = user_id)
        update_user.first_name = request.POST['first_name']
        update_user.last_name = request.POST['last_name']
        update_user.email = request.POST['email']
        update_user.save()
        print "success"
        return redirect(reverse('users:index'))
    else:
        return redirect(reverse('users:edit', kwargs={"user_id" : user_id}))


# Create your views here.

django_projects/semi_restful_users/apps/users/templates/users/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <link rel="stylesheet" href="styles.css">
  
   <title>Update User</title>
</head>
<body>
    <div class="container">
    <h2> Update User {{users.id}}</h2>
     {% for x in request.session.errors %}
    <div class="alert">
    <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        {{x}}
</div> {% endfor %}
    
    
    <form action="{% url 'users:update' users.id %}" method='post'>
        {% csrf_token %} 
        <div class="form-group">
            <label for="formGroupExampleInput">First Name</label>
            <input type="text" class="form-control" name="first_name" id="first_name" value = "{{users.first_name}}">
        </div>
         <div class="form-group">
            <label for="formGroupExampleInput">Last Name</label>
            <input type="text" class="form-control" name="last_name" value = "{{users.last_name}}" id="last_name">
        </div>
            <label for="formGroupExampleInput">Email</label>
            <input type="text" class="form-control" name="email" value = "{{users.email}}"id="email">
        </div>

        <div>
            <input type=submit value=Update>
        </div>
    </form>
    </div>

</body>
</html>

django_projects/semi_restful_users/apps/users/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <link rel="stylesheet" href="styles.css">
   <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
   <script src=" "></script>
   <title>User Index</title>
</head>
<body>
   <h1>Users</h1>
  
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-highlight">
            <thead>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>Created At</th>
                <th>Actions</th>
                </thead>
            <tbody>
             {% for user in all_users %}
            <tr>
                <td>{{user.id}}</td>
                <td>{{user.first_name}} {{user.last_name}}</td>
                <td>{{user.email}}</td>
                <td>{{user.created_at}}</td>
                <td><a href="{% url 'users:show' user.id %}"><button>Show</button></a><a href="{% url 'users:edit' user.id %}"><button>Edit</button></a><a href="{% url 'users:destroy' user.id %}"><button>Delete</button></a></td>
            </tr>
             {% endfor %} 
             

            </tbody>
        </table>
    </div>
</form>
<a href="{% url 'users:new' %}"><button>Add A New User</button></a>
</body>
</html>

django_projects/semi_restful_users/apps/users/templates/users/new.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <link rel="stylesheet" href="styles.css">
  
   <title>New User</title>
</head>
<body>
    <div class="container">
    <h2> Add A New User</h2>
    <form action="{% url 'users:create' %}" method='post'>
        {% csrf_token %} 
        <div class="form-group">
            <label for="formGroupExampleInput">First Name</label>
            <input type="text" class="form-control" name="first_name" id="first_name">
        </div>
         <div class="form-group">
            <label for="formGroupExampleInput">Last Name</label>
            <input type="text" class="form-control" name="last_name" id="last_name">
        </div>
            <label for="formGroupExampleInput">Email</label>
            <input type="text" class="form-control" name="email" id="email">
        </div> 
        <div>
            <input type=submit value=Create>
        </div>
    </form>
    </div>

</body>
</html>

django_projects/semi_restful_users/apps/users/templates/users/show.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <link rel="stylesheet" href="styles.css">
   <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
   <script src=" "></script>
   <title>User Show</title>
</head>
<body>
   <h1>User {{users.id}}</h1>
   <h3>Full Name : {{users.first_name}}{{users.last_name}}</h3>
   <h3>Email : {{users.email}}</h3>
   <h3>Created At : {{users.created_at}}</h3>
   <a href="{% url 'users:edit' users.id %}"><button>Edit</button></a><a href="{% url 'users:destroy' users.id %}"><button>Delete</button></a>
</body>
</html>